version: "3.9"
services:
  postgres-test:
    image: postgres:15
    container_name: postgres-test
    environment:
      POSTGRES_DB: "users"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
